#!/bin/sh

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

set -u
set -e

# Print executed commands for debugging
[ -n "$debug" ] && set -x

. /scripts/functions


# Wait for system partition
log_begin_msg "Waiting for system partition to become available"

if [ -z "${FSUUID}" ]; then
    log_failure_msg "Can't find system partition: FSUUID is not set. Skipping restoring random seed."
    exit 0
fi

success=
i=0
while [ "$i" -lt 300 ]; do
    if [ -b "/dev/disk/by-uuid/${FSUUID}" ]; then
        SYSTEM_PARTITION=$(readlink -f "/dev/disk/by-uuid/${FSUUID}")
        PARENT_PATH=$(udevadm info --query=property --name="${SYSTEM_PARTITION}" \
            | grep ^ID_PATH= | sed s/ID_PATH=//)
        PARENT_DEVICE=$(readlink -f "/dev/disk/by-path/${PARENT_PATH}")
        if [ -b "${PARENT_DEVICE}" ]; then
            success=1
            break
        fi
    fi
    sleep 0.2
    i="$(($i + 1))"
done

if [ -n "$success" ]; then
  log_end_msg
else
  log_failure_msg "Reached timeout waiting for system partition. Skipping restoring random seed."
  exit 0
fi

log_begin_msg "Restoring random seed from LBA 34"
dd bs=512 skip=34 count=1 if="${PARENT_DEVICE}" of=/dev/urandom
# Refresh seed
dd bs=512 seek=34 count=1 if=/dev/urandom of="${PARENT_DEVICE}"
log_end_msg

exit 0
