#!/bin/sh

PREREQS="plymouth"

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
        prereqs
        exit 0
        ;;
esac

set -u
set -e

# Print executed commands for debugging
[ -n "${debug}" ] && set -x

. /scripts/functions

if [ -z "${FSUUID:-}" ]; then
    echo "\$FSUUID is unset, probably because the boot medium is an ISO." \
        "Not restoring random seed from LBA 34."
    exit 0
fi

# Wait for system partition
log_begin_msg "Waiting for system partition to become available"
i=0
while true; do
    if [ -b "/dev/disk/by-uuid/${FSUUID}" ]; then
        SYSTEM_PARTITION="$(readlink -f "/dev/disk/by-uuid/${FSUUID}")"
        PARENT_PATH="$(udevadm info --query=property --name="${SYSTEM_PARTITION}" |
            sed -n '/^ID_PATH=/ s/^ID_PATH=// p')"
        PARENT_DEVICE="$(readlink -f "/dev/disk/by-path/${PARENT_PATH}")"
        if [ -b "${PARENT_DEVICE}" ]; then
            break
        fi
    fi

    if [ "$i" -ge 300 ]; then
        log_failure_msg "Reached timeout waiting for system partition." \
            "Not restoring random seed from LBA 34."
        exit 0
    fi

    sleep 0.2
    i="$((i + 1))"
done
log_end_msg

log_begin_msg "Restoring random seed from LBA 34"
dd bs=512 skip=34 count=1 if="${PARENT_DEVICE}" of=/dev/urandom
# Refresh seed
dd bs=512 seek=34 count=1 if=/dev/urandom of="${PARENT_DEVICE}"
log_end_msg

exit 0
