#!/bin/sh

set -e
set -u

PREREQ=""

prereqs () {
	echo "${PREREQ}"
}

if [ ! -z ${1+x} ]; then
	case "${1}" in
		prereqs)
			prereqs
			exit 0
			;;
	esac
fi

. /usr/share/initramfs-tools/hook-functions

manual_add_modules amdgpu bochs-drm cirrus i915 nouveau qxl radeon

exit 0
