#!/bin/sh -e

PREREQS=""

prereqs() { echo "$PREREQS"; }

case "$1" in
    prereqs)
    prereqs
    exit 0
    ;;
esac

# Copy random seed bytes from the root device sector located just
# after the GPT table to urandom and systemd entropy pools.
# These bytes are written by the Tails Installer.
# This only works for writable devices such as USB sticks.

MIN_SECTOR_SIZE_BYTES=512
RANDOM_SEED_SECTOR=35

RANDOM_SEED_SYSTEMD="$rootmnt/var/lib/systemd/random-seed"
RANDOM_SEED_URANDOM="$rootmnt/var/lib/urandom/random-seed"
URANDOM_DIR="$rootmnt/var/lib/urandom"

# Magic value "seed" located before the actual seed if present
MAGIC_NUMBER_OFFSET=$(($RANDOM_SEED_SECTOR*$MIN_SECTOR_SIZE_BYTES-4))

ROOT_DEVICE=$(cat /proc/self/mounts | grep "$rootmnt/lib/live/mount/medium" \
              | awk '{print $1}' | sed 's/[0-9]\+$//')

if [ "$ROOT_DEVICE" = "" ]; then
    exit 0
fi;

# Find if there is a random seed present.
# Otherwise we could wrongly copy zero or garbage bytes.
MAGIC_NUMBER=$(dd if=$ROOT_DEVICE skip=$MAGIC_NUMBER_OFFSET ibs=1 count=4 | strings)

. /scripts/functions
# If seed present
if [ "$MAGIC_NUMBER" = "seed" ]; then
    log_begin_msg "Initializing random number generator..."
    # Carry a random seed from start-up to start-up
    # Load and then save the whole entropy pool
    # cat $random_seed >/dev/urandom
    dd bs=$MIN_SECTOR_SIZE_BYTES if=$ROOT_DEVICE of=/dev/urandom \
       skip=$RANDOM_SEED_SECTOR count=1
    # Create urandom directory and seed file if it does not exist
    if [ ! -f "$RANDOM_SEED_URANDOM" ]; then
        mkdir "$URANDOM_DIR"
        touch "$RANDOM_SEED_URANDOM"
    fi;
    # Update both urandom and systemd seed files
    dd if=/dev/urandom of=$RANDOM_SEED_URANDOM count=1 bs=$MIN_SECTOR_SIZE_BYTES
    chmod 600 $RANDOM_SEED_URANDOM
    dd if=/dev/urandom of=$RANDOM_SEED_SYSTEMD count=1 bs=512
    # Creaye a new random seed after the GPT table
    dd bs=$MIN_SECTOR_SIZE_BYTES if=/dev/urandom of=$ROOT_DEVICE \
       skip=$RANDOM_SEED_SECTOR count=1
    log_end_msg
fi;

exit 0
