#!/bin/sh

set -e
set -u

# We're a no-op unless running as the default desktop user
[ "$(/usr/bin/id -u)" = 1000 ] || exit 0

. /usr/local/lib/tails-shell-library/gtk.sh

add_gtk_bookmark_for "${HOME}/Tor Browser"
