#!/bin/sh

###
# This script is showing a notification explaining the user that time syncing has just started

set -e
set -u

# Get LIVE_USERNAME
# shellcheck source=../../live/config.d/username.conf
. /etc/live/config.d/username.conf

# Import export_gnome_env().
# shellcheck source=../../../usr/local/lib/tails-shell-library/gnome.sh
. /usr/local/lib/tails-shell-library/gnome.sh

### Exit conditions

### Functions

start_notification_helper() {
	export_gnome_env
	exec /bin/su -c /usr/local/lib/tails-htp-notify-user "$LIVE_USERNAME" &
}


### Main

start_notification_helper
