#!/bin/sh

set -e
set -u

# Import try_for()
. /usr/local/lib/tails-shell-library/common.sh
# Import tor_set_in_torrc()
. /usr/local/lib/tails-shell-library/tor.sh

ENABLE_SANDBOX="${1}"

if [ "${ENABLE_SANDBOX}" != 0 ] && [ "${ENABLE_SANDBOX}" != 1 ]; then
    echo "error: bad argument: ${ENABLE_SANDBOX}" >&2
    exit 1
fi

if [ "$(/usr/local/lib/tor_variable get --type=conf Sandbox)" = "${ENABLE_SANDBOX}" ]; then
    exit 0
fi

systemctl stop tor@default.service

tor_set_in_torrc Sandbox "${ENABLE_SANDBOX}"
sed -i '/^ClientTransportPlugin /d' /etc/tor/torrc
if [ "${ENABLE_SANDBOX}" = 0 ]; then
    tor_append_to_torrc 'ClientTransportPlugin obfs2,obfs3,obfs4,meek_lite exec /usr/bin/obfs4proxy -enableLogging -unsafeLogging -logLevel DEBUG'
    tor_append_to_torrc 'ClientTransportPlugin snowflake exec /usr/bin/snowflake-client -url https://snowflake-broker.torproject.net.global.prod.fastly.net/ -front cdn.sstatic.net -ice stun:stun.l.google.com:19302,stun:stun.voip.blackberry.com:3478,stun:stun.altar.com.pl:3478,stun:stun.antisip.com:3478,stun:stun.bluesip.net:3478,stun:stun.dus.net:3478,stun:stun.epygi.com:3478,stun:stun.sonetel.com:3478,stun:stun.sonetel.net:3478,stun:stun.stunprotocol.org:3478,stun:stun.uls.co.za:3478,stun:stun.voipgate.com:3478,stun:stun.voys.nl:3478'
fi

systemctl start tor@default.service
