#!/bin/sh

set -e

# Create the procfs_priv group.
#
# (Re-)Mounting /proc with hidepid=2 prevents users from seeing other users processes. Users in the group procfs_priv will not be subject to this restriction

echo "Creating the procfs group"

addgroup --system --quiet --gid 151 procfs_priv
