#!/bin/sh

set -e
set -u

# Without this wrapper, after closing Nautilus, one gets the prompt back
# only after 5-15 seconds, which confuses users and makes our doc more
# complicated than it should (#12034, #10391). So let's start Nautilus
# silently in the background instead.

exec /usr/bin/nautilus "$@" 2>/dev/null &
